<a href="https://colab.research.google.com/github/ZahinAbrar/Alternating-Direction-Method-Of-Multipliers/blob/main/For_Playing_with_NoMAD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing numpy library
import numpy as np  
  
# random is a function, doing random sampling in numpy.
array = np.random.randint(10, size=(5,3))
  
# the array will be having 20 elements.
print(array)

[[8 0 2]
 [1 5 6]
 [2 6 7]
 [4 6 8]
 [9 2 8]]


In [ ]:
# importing numpy library
import numpy as np  
  
# random is a function, doing random sampling in numpy.
array = np.random.randint(10, size=(5,5))
  
# the array will be having 20 elements.
print(array)
# print(array[3,0])
# print(array[0,0])
# print(array[0,1])
# print(array[1,1])
# dis_12= np.divide (array[0,1], np.multiply(array[0,0], array[1,1]))
# print(dis_12)
print(np.zeros(shape=(5,5)))

[[0 9 1 3 3]
 [4 4 1 1 2]
 [4 6 0 3 6]
 [2 2 4 3 4]
 [4 4 6 3 1]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# importing numpy library
import numpy as np  
  
# random is a function, doing random sampling in numpy.
array = np.random.randint(10, size=(5,5))
print(array)
row_i=array[3,:]
leaves=[4];
print(row_i)
a=np.count_nonzero(row_i)
b=np.nonzero(a)
print(b)
# leaves.append(a)
# print(leaves)
# print(a)


[[3 9 2 2 7]
 [6 2 8 6 0]
 [1 0 9 5 2]
 [8 1 3 7 3]
 [1 9 4 9 6]]
[8 1 3 7 3]
(array([0]),)


In [ ]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x[2,:])
print(np.nonzero(x[2,:]))


[5 6 0]
(array([0, 1]),)


In [ ]:
x= ([1], [1,2,3])
y=[2], [1,2,3,3]
z=x,y
print(z)


(([1], [1, 2, 3]), ([2], [1, 2, 3, 3]))


In [ ]:
import numpy as np
x= ([1], [1,2,3]), ([2], [1,2,3,3])
# print(x)
# print(len(x))
listvals = []
for i in range(0,len(x)):
  listvals.append(x[i])
print(listvals)
print(listvals[1])


[([1], [1, 2, 3]), ([2], [1, 2, 3, 3])]
([2], [1, 2, 3, 3])


In [ ]:
import math
print(math.comb(5, 3))

10


In [ ]:
import itertools
a_list= [1, 2, 3, 4];
all_combinations = []
for r in range(len(a_list) + 1):
  combinations_object = itertools.combinations(a_list, 3)
  combinations_list = list(combinations_object)
  # all_combinations += combinations_list

print(combinations_list)






[(1, 2, 3), (1, 2, 4), (1, 3, 4), (2, 3, 4)]
(1, 2, 3)


In [ ]:
## code for full distance list or distance list look up table ## 

a=(1,2,3)
for r in range(len(a) + 1):
  combinations_object = itertools.combinations(a, 2)
  combinations_list = list(combinations_object)
  # all_combinations += combinations_list

print(combinations_list)
print(len(combinations_list))

distantce_list=[]
for i in range(0,len(combinations_list)):
  listvals=[[],[]]
  listvals[0].append(combinations_list[i])
  listvals[1].append(12+i) # this i has been added for testing 
  distantce_list.append(listvals)
print(listvals)
print(distantce_list)

# k=2,l=3;
# for i in range(0,len(distantce_list)):
#   if i[0]==k & i[1]==l:

print(listvals)
print(distantce_list)





[(1, 2), (1, 3), (2, 3)]
3
[[(2, 3)], [14]]
[[[(1, 2)], [12]], [[(1, 3)], [13]], [[(2, 3)], [14]]]
[[(2, 3)], [14]]
[[[(1, 2)], [12]], [[(1, 3)], [13]], [[(2, 3)], [14]]]


In [ ]:
## distance compuation between ancestor and all the vertices in a triplet

def Triple_Anc_Dis(V):
  triple_anc_dist=[];
  for i in range(0,len(V)):
      listvals=[[],[]]
      listvals[0].append(V[i])
      listvals[1].append(12 + V[i]) # this i has been added for testing 
      triple_anc_dist.append(listvals)
  print(triple_anc_dist)

Triple_Anc_Dis([8,2,3])
  

[[[8], [20]], [[2], [14]], [[3], [15]]]


In [ ]:
## Need to think about it more ##

def Triple_Anc_Dis(V):
  dist_dict= {V[0]: [12], V[1]: [14], V[2]: [17]} # complete the ramining in the spare time
  print(dist_dict[V[0]])
  print(dist_dict[V[1]])
  print(dist_dict[V[2]])

# myDict=
Triple_Anc_Dis([5,6,7]);
# print(myDict[5])



[12]
[14]
[17]


In [ ]:
myDict = {1: [1, 2, 3, 4, 5],
          2: [2, 3, 4, 5, 6],
          3: [3, 4, 5, 6, 7]}
print(myDict[3])

[3, 4, 5, 6, 7]


In [ ]:
list(itertools.combinations(a_list, 2))

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]

In [ ]:
list_of_numbers = list(range(1, 6))

print(list_of_numbers)  


[1, 2, 3, 4, 5]


In [ ]:
import numpy as np  
d=5;  
# random is a function, doing random sampling in numpy.
array = np.random.randint(10, size=(d,d))
print(np.linalg.inv(array))
print(array)
print(array[0,2])
array_try= np.zeros(shape=(d,d))
for i in range(0,d):
  for j in range(0,d):
    if i ==j:
      array_try[i,j]=0
    else:
      array_try[i,j]=  np.divide (array[i,j], np.sqrt(np.multiply(array[i,i], array[j,j]))) 





[[-0.08940719  0.10398445 -0.4606414   0.44606414 -0.16520894]
 [ 0.05344995 -0.18172983  0.25364431 -0.12536443  0.12050534]
 [-0.0202138   0.18872692  0.03498542 -0.00349854 -0.17648202]
 [-0.06511176  0.02137998  0.3819242  -0.33819242  0.16229349]
 [ 0.14480078 -0.09232264 -0.05830904  0.0058309   0.07191448]]
[[2 2 5 2 9]
 [6 0 5 8 8]
 [5 7 5 4 3]
 [9 8 5 6 6]
 [7 1 0 9 8]]
5


<ipython-input-42-5d538644a70e>:14: RuntimeWarning: divide by zero encountered in true_divide
  array_try[i,j]=  np.divide (array[i,j], np.sqrt(np.multiply(array[i,i], array[j,j])))


In [ ]:
def Triple_Anc_Dis(V):
  dist_dict= {V[0]: [12], V[1]: [14], V[2]: [17]} # correct this line in the spare time
  print(dist_dict[V[0]])
  print(dist_dict[V[1]])
  print(dist_dict[V[2]])

Triple_Anc_Dis([4,5,6])

[12]
[14]
[17]


In [ ]:
import numpy as np
def Triple_Anc_Dis(V):
  dist_dict= {V[0]: [12], V[1]: [14], V[2]: [17]} # correct this line in the spare time
  return dist_dict
W=[4,5,6]
dist= Triple_Anc_Dis(W);
# W_int=[int(x) for x in W]
a=dist[W_int[0]]
b=dist[W_int[1]]
# W_a=[int(x) for x in a]
# W_b=[int(x) for x in b]
print(a)
print(b)
W_a=[1]; W_b=[2]
print(np.add(dist[W_int[0]],dist[W_int[1]]))


[12]
[14]
[26]


In [ ]:
import itertools
import numpy as np
def Pairs_of_Triple(V):
  for r in range(len(V) + 1):
    combinations_object = itertools.combinations(V,2)
    vtx_pairs = list(combinations_object)
  return vtx_pairs
  # print(vtx_pairs)

Pairs_of_Triple([4,5,6])
print(Pairs_of_Triple([4,5,6])[0])
print(np.sum(Pairs_of_Triple([4,5,6])[0]))

(4, 5)
9


In [ ]:
def TIA_test(U,V):
  U_Anc_dist= Triple_Anc_Dis(U);
  V_Anc_dist= Triple_Anc_Dis(V);
  V_pairs=Pairs_of_Triple(V)
  tot_cnt=0;
  for i in U:
    i_cnt=0;
    for j in V_pairs:
      j_cnt=0;
      if U_Anc_dist[U[1]]==np.sum(V_pairs[j]):   # another option np.add(V_pairs[j][0],V_pairs[j][1])
        j_cnt=j_cnt+1
    if J_cnt >1:
      i_cnt=i_cnt+1
      tot_cnt=tot_cnt+1
  if tot_cnt ==3:
    #U,V are star triplets





In [ ]:
import numpy as np
# K = [0.1 0 0.05 0 0 0; 0 0.1 0.05 0 0 0; 0.05 0.05 .1 0.05 0 0; 0 0 0.05 1 0.05 0.05; 0 0 0 0.05 .075 .06; 0 0 0 .05 .06 .075];
A=np.matrix([[1, 2], [3, 4]]);
B=np.matrix([[2, 3], [4, 5]]);
C=np.matrix([[2.2, 3], [4, 5], [6,7]]);
K=np.matrix([[0.1, 0, 0.05, 0, 0, 0], [0, 0.1, 0.05, 0, 0, 0], [0.05, 0.05, .1, 0.05, 0, 0],[0, 0, 0.05, 1, 0.05, 0.05], [0, 0, 0, 0.05, .075, .06],[0, 0, 0, .05, .06, .075]]);
# K=np.matrix([[0.1, 0, 0.05, 0, 0, 0],,[0, 0, 0, 0.05, .075, .06] [0, 0, 0, .05, .06, .075]]);
print(K)


[[0.1   0.    0.05  0.    0.    0.   ]
 [0.    0.1   0.05  0.    0.    0.   ]
 [0.05  0.05  0.1   0.05  0.    0.   ]
 [0.    0.    0.05  1.    0.05  0.05 ]
 [0.    0.    0.    0.05  0.075 0.06 ]
 [0.    0.    0.    0.05  0.06  0.075]]


In [ ]:
from numpy.linalg import inv
d=np.random.randint(0.5, high=30, size=6, dtype=int)
D=np.diag(d)
print(D)
c=np.linalg.inv(K)
print(c)


[[24  0  0  0  0  0]
 [ 0 20  0  0  0  0]
 [ 0  0 18  0  0  0]
 [ 0  0  0 12  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0 12]]
[[ 15.27383367   5.27383367 -10.54766734   0.54766734  -0.20283976
   -0.20283976]
 [  5.27383367  15.27383367 -10.54766734   0.54766734  -0.20283976
   -0.20283976]
 [-10.54766734 -10.54766734  21.09533469  -1.09533469   0.40567951
    0.40567951]
 [  0.54766734   0.54766734  -1.09533469   1.09533469  -0.40567951
   -0.40567951]
 [ -0.20283976  -0.20283976   0.40567951  -0.40567951  37.18728871
  -29.47937796]
 [ -0.20283976  -0.20283976   0.40567951  -0.40567951 -29.47937796
   37.18728871]]
